name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  analyze:
    name: Flutter Analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6' # .fvmrc 와 일치시킬 것
          channel: stable
          cache: true

      - name: Restore secret files
        env:
          KEYS_DART: ${{ secrets.KEYS_DART }}
          CONFIG_DART: ${{ secrets.CONFIG_DART }}
        run: |
          echo "$KEYS_DART" > lib/auth/keys.dart
          echo "$CONFIG_DART" > lib/config.dart

      - run: flutter pub get

      - run: flutter analyze --no-pub

  test:
    name: Flutter Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.44.6' # .fvmrc 와 일치시킬 것
          channel: stable
          cache: true

      - name: Restore secret files
        env:
          KEYS_DART: ${{ secrets.KEYS_DART }}
          CONFIG_DART: ${{ secrets.CONFIG_DART }}
        run: |
          echo "$KEYS_DART" > lib/auth/keys.dart
          echo "$CONFIG_DART" > lib/config.dart

      - run: flutter pub get

      - run: flutter test --no-pub --coverage

      - name: Verify coverage threshold
        uses: VeryGoodOpenSource/very_good_coverage@v3
        with:
          path: coverage/lcov.info
          min_coverage: 83
